
HARD_CHARACTERS = {c for c in "ABCDEFGIJKLMNOPRSTUVYZ"}
ANNOTATION_CHARACTERS = {c for c in ",.|~_()"}
ASPIRATE = "'"
MEDIUM_SOUND = "."
LONG_SOUND = ","
LOOP = "|"
REVERSE = "~"
WUNDERBAR = "_"
ING = "'"
LEFT = "("
RIGHT = ")"
OBLIQUE = ","
DISJOINER = "^"
BOUNDARY = "-"
INTERSECTION = "\\"

_CIRCLE_VOWEL_ANNOTATIONS = [(REVERSE,), (LOOP,), (MEDIUM_SOUND, LONG_SOUND), (WUNDERBAR,)]
_CIRCLE_DIPHTHONG_ANNOTATIONS = [(REVERSE,), (LOOP,), (WUNDERBAR,)]
_HOOK_DIPHTHONG_ANNOTATIONS = [(WUNDERBAR,)]
_DIRECTED_CONSONANT_ANNOTATIONS = [(LEFT, RIGHT), (OBLIQUE,)]

ANNOTATIONS = {
    "A": _CIRCLE_VOWEL_ANNOTATIONS,
    "E": _CIRCLE_VOWEL_ANNOTATIONS,
    "O": [(LEFT,), (MEDIUM_SOUND, LONG_SOUND), (WUNDERBAR,)],
    "U": [(RIGHT,), (MEDIUM_SOUND, LONG_SOUND), (WUNDERBAR,)],
    "I": _CIRCLE_DIPHTHONG_ANNOTATIONS,
    "A&'": _CIRCLE_DIPHTHONG_ANNOTATIONS,
    "A&E": _CIRCLE_DIPHTHONG_ANNOTATIONS,
    "EU": _HOOK_DIPHTHONG_ANNOTATIONS,
    "AU": _HOOK_DIPHTHONG_ANNOTATIONS,
    "OE": _HOOK_DIPHTHONG_ANNOTATIONS,
    "S": _DIRECTED_CONSONANT_ANNOTATIONS,
    "Z": _DIRECTED_CONSONANT_ANNOTATIONS,
    "TH": _DIRECTED_CONSONANT_ANNOTATIONS,
    "SH": [(OBLIQUE,)]
}
