[build-system]
requires = ["setuptools", "wheel", "lark~=1.0"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.isort]
profile = "black"
add_imports=["from __future__ import annotations"]

[tool.pytest.ini_options]
markers = [
  "slow: mark test as slow."
]
